version: "3.3"
#name: docker_flask_mysql
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - ${APP_PORT}:5000
    volumes:
      - ./app:/app
    networks:
      net_app:
        ipv4_address: 172.16.20.2
    container_name: Python
  db:
    image: ${MYSQL_VERSION}
#    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database/:/var/lib/mysql
    networks:
      net_app:
        ipv4_address: 172.16.20.3
    container_name: Mysql
networks:
  net_app:
        ipam:
            config:
              - subnet: 172.16.20.1/29
 
